### ISSUE TITLE
Warning you forked a scammer repo! checkout the original one

### ISSUE THREAD

**Issue by z1poc** [FroggMaster/ESP32-Wi-Fi-Penetration-Tool#6]
Hi FroggMaster.
this guy 0x1381 is pretending to be the author of the project
https://github.com/0x1381/ESP32-Wi-Fi-Penetration-Tool
he just re-uploaded everything, changed the author in main.c 
and remove some proof that show the original author like removing youtube video of the original author:
https://github.com/0x1381/ESP32-Wi-Fi-Penetration-Tool/commit/f37a642794ab91b34a5a303236db344a6a7f71fa

the original autor is this user risinek. he also wrote an university thesis about his project.
https://github.com/risinek/esp32-wifi-penetration-tool.

please consider adding your work to the genuine repo. I saw that you introduce 17 commits 

bye

**Comment by FroggMaster** [comment]
Thank you for notifying me; I've submitted a ticket with Github support to have my fork re-routed to the appropriate project. :) I appreciate you taking the time to let me know.
